version: 0
managers:
  mars: &mars
    server: "https://mars.q.ngrok.com"
    token: null
  vaughan: &vaughan
    server: "https://vaughan.ngrok.com"
    token: null
  vaughan-2: &vaughan-2
    server: "https://vaughan-2.ngrok.com"
    token: null

mounts: # mount configurations Available keys: NOW, UUID,
  - !mounts.TarMount &code_mount
    local_path: .
    host_path: $JYNMNT/main_code
    snapshot_path:  $JYNMNT/{now:%Y-%m-%d}/main_code/{now:%H%M%S.%f}
    # container_path: /Users/geyang/learning-to-learn
    pypath: true
    excludes: "--exclude='*__pycache__' --exclude='*.git' --exclude='*.idea' --exclude='*.egg-info' --exclude='*.pkl'"
    compress: true

runners:
  - !runners.SlurmManager &mars
    envs: >-
      LD_LIBRARY_PATH=/public/apps/anaconda3/5.0.1/lib:/private/home/geyang/.mujoco/mjpro150/bin::/public/slurm/17.11.4/lib
    startup: >-
      source /etc/profile;
      source ~/.profile;
      module load anaconda3/5.0.1;
      source activate playground;
      export LC_CTYPE=en_US.UTF-8
    # cd {mounts[0].host_path} && pip install -e . -q
    pypath: "{mounts[0].host_path}"
    launch_directory: "{mounts[0].host_path}"
    partition: "dev,priority,uninterrupted"
    time_limit: "0:0:20"
    n_cpu: 40
    n_gpu: 0
  - !runners.Slurm &lnl_slurm
    envs: "LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8 LANGUAGE=en_US SSH_TTY=/dev/pts/1 TERM=xterm-256color"
    startup: >-
      source /etc/profile;
      source ~/.profile;
      module load anaconda3/5.0.1;
      source activate playground;
      export LC_CTYPE=en_US.UTF-8
    pypath: "{mounts[0].host_path}/rl:{mounts[0].host_path}/imitation:{mounts[0].host_path}/rl_maml_tf"
    launch_directory: "{mounts[0].host_path}"
    partition: "" # not clear what the partition is like
    time_limit: "0:0:20"
    n_cpu: 40
    n_gpu: 0

modes: # todo: add support to modes.
  oberyn:
    mounts:
      - *code_mount
    runner: *ssh_docker
    launch:
      type: ssh
      <<: *oberyn
  hodor:
    mounts:
      - *code_mount
    runner: *ssh_docker
    launch:
      type: ssh
      <<: *hodor
  ec2:
    mounts:
      - *code_mount
    runner: *ssh_docker
    host:
      terminate_after: true
    launch:
      type: ec2
      <<: *ec2
  fair:
    mounts:
      - *fair_code_mount
    runner: *fair_slurm
    launch:
      type: ssh
      <<: *dev_fair
    # the problem: we need to use the correct logging files
    launch_log: /private/home/geyang/jaynes-launch.log
    launch_error: /private/home/geyang/jaynes-launch.err.log
  savio:
    mounts:
      - *fair_code_mount
    runner: *lnl_slurm
    launch:
      type: ssh
      <<: *savio
